In [27]:
import os
import re
import sys

import pdfplumber
import pandas as pd
import numpy as np

import os
import sys

project_root = os.path.abspath("..")
sys.path.append(project_root)

print(project_root)

c:\college predictor

In [10]:
PROJECT_ROOT = ".."

RAW_DATA_PATH = os.path.join(PROJECT_ROOT, "dataset", "raw")
EXTRACTED_DATA_PATH = os.path.join(PROJECT_ROOT, "dataset", "extracted")
CLEANED_DATA_PATH = os.path.join(PROJECT_ROOT, "dataset", "cleaned")

os.makedirs(EXTRACTED_DATA_PATH, exist_ok=True)
os.makedirs(CLEANED_DATA_PATH, exist_ok=True)

print("Project folders ready!")

Project folders ready!

In [11]:
pdf_files = []

for root, dirs, files in os.walk(RAW_DATA_PATH):
    for file in files:
        if file.endswith(".pdf"):
            pdf_files.append(os.path.join(root, file))

print(f"Found {len(pdf_files)} PDF(s):\n")

for pdf in pdf_files:
    print(pdf)

Found 3 PDF(s):

..\dataset\raw\2023-2024\2023-2024.pdf
..\dataset\raw\2024-2025\2024-2025.pdf
..\dataset\raw\2025-2026\2025-2026.pdf

In [12]:
pdf_path = pdf_files[0]

with pdfplumber.open(pdf_path) as pdf:
    print("Pages:", len(pdf.pages))

Pages: 1485

In [13]:
with pdfplumber.open(pdf_path) as pdf:
    page = pdf.pages[0]
    text = page.extract_text()

print(text[:3000])

D Government of Maharashtra
i State Common Entrance Test Cell
r Cut Off List for Maharashtra & Minority Seats of CAP Round I for Admission to First Year of Four Year
Degree Courses In Engineering and Technology & Master of Engineering and Technology (Integrated 5 Years) for the Year 2023-24
1002 - Government College of Engineering, Amravati
100219110 - Civil Engineering
Status: Government Autonomous
State Level
Stage GOPENS GSCS GSTS GVJS GNT1S GNT2S GNT3S GOBCS LOPENS LSCS LSTS LVJS LNT1S LNT2S LNT3S LOBCS PWDOPENS DEFOPENS TFWS EWS
I 45820 54803 85528 53198 55202 47207 58799 55212 39555 58069 81275 55889 71604 59895 85506 50933 66222 114710 25437 51497
(80.7328826) (76.6166542) (58.7429854) (76.9213416) (76.2843676) (79.8081214) (74.1935484) (76.2843676) (83.4053417) (75.0737739) (61.4332053) (75.8673530) (67.3938217) (73.6426530) (58.7429854) (78.3308876) (70.5106049) (36.1619626) (89.6901790) (78.0675570)
100224210 - Computer Science and Engineering
Status: Government Autonomous
State Level
Stage GOPENS GSCS GSTS GVJS GNT1S GNT2S GNT3S GOBCS LOPENS LSCS LSTS LOBCS PWDOPENS DEFOPENS TFWS PWDROBC DEFROBCS EWS
S
I 6839 14995 42063 10351 13430 10052 15513 7626 7359 18093 46043 8159 41373 14766 6790 45737 16792 10297
(97.3642653) (94.0441452) (82.3107244) (95.9541871) (94.6808113) (96.0633178) (93.8260094) (97.0482604) (97.1523959) (92.7333060) (80.6210251) (96.8581856) (82.4643661) (94.1664477) (97.3792778) (80.8641005) (93.2969235) (95.9738402)
100224610 - Information Technology
Status: Government Autonomous
State Level
Stage GOPENS GSCS GSTS GVJS GNT1S GNT2S GNT3S GOBCS LOPENS LSCS LSTS LNT1S LNT2S LOBCS PWDOPENS DEFOPENS TFWS PWDRSCS DEFROBCS EWS
I 10303 18667 43516 23597 16268 12552 16999 11044 9567 21001 55122 16115 12233 10354 66253 30013 9138 71173 30456 12526
(95.9738402) (92.4862529) (81.8534982) (90.4575998) (93.5213570) (95.0744473) (93.2108027) (95.6795422) (96.2787373) (91.4895289) (76.2843676) (93.5868331) (95.2175544) (95.9541871) (70.5106049) (87.6984872) (96.4414768) (67.7119280) (87.4817577) (95.0827713)
100229310 - Electrical Engineering
Status: Government Autonomous
State Level
Stage GOPENS GSCS GSTS GVJS GNT1S GNT2S GOBCS LOPENS LSCS LSTS LVJS LNT3S LOBCS DEFOPENS TFWS EWS
I 31193 45777 92626 39357 42146 47720 34759 26636 34812 121868 32994 87211 31414 92685 24140 37774
(87.2113119) (80.7328826) (54.0043616) (83.4300164) (82.2515860) (79.7807688) (85.4752553) (89.1600241) (85.4752553) (29.2444305) (86.3550668) (58.0840122) (87.0556299) (54.0043616) (90.1850615) (84.2884307)
Legends: Starting character G-General, L-Ladies, End character H-Home University, O-Other than Home University,S-State Level, AI- All India Seat.
Maharashtra State Seats - Cut Off Indicates Maharashtra State General Merit No.; Figures in bracket Indicates Merit Percentile.
1

In [14]:
import pdfplumber

pdf_path = pdf_files[0]

for i in [0, 5, 10, 20, 50, 100, 150]:
    with pdfplumber.open(pdf_path) as pdf:
        text = pdf.pages[i].extract_text()

    print("=" * 80)
    print(f"PAGE {i + 1}")
    print("=" * 80)

    if text:
        print(text[:1500])
    else:
        print("No text found")

================================================================================
PAGE 1
================================================================================
D Government of Maharashtra
i State Common Entrance Test Cell
r Cut Off List for Maharashtra & Minority Seats of CAP Round I for Admission to First Year of Four Year
Degree Courses In Engineering and Technology & Master of Engineering and Technology (Integrated 5 Years) for the Year 2023-24
1002 - Government College of Engineering, Amravati
100219110 - Civil Engineering
Status: Government Autonomous
State Level
Stage GOPENS GSCS GSTS GVJS GNT1S GNT2S GNT3S GOBCS LOPENS LSCS LSTS LVJS LNT1S LNT2S LNT3S LOBCS PWDOPENS DEFOPENS TFWS EWS
I 45820 54803 85528 53198 55202 47207 58799 55212 39555 58069 81275 55889 71604 59895 85506 50933 66222 114710 25437 51497
(80.7328826) (76.6166542) (58.7429854) (76.9213416) (76.2843676) (79.8081214) (74.1935484) (76.2843676) (83.4053417) (75.0737739) (61.4332053) (75.8673530) (67.3938217) (73.6426530) (58.7429854) (78.3308876) (70.5106049) (36.1619626) (89.6901790) (78.0675570)
100224210 - Computer Science and Engineering
Status: Government Autonomous
State Level
Stage GOPENS GSCS GSTS GVJS GNT1S GNT2S GNT3S GOBCS LOPENS LSCS LSTS LOBCS PWDOPENS DEFOPENS TFWS PWDROBC DEFROBCS EWS
S
I 6839 14995 42063 10351 13430 10052 15513 7626 7359 18093 46043 8159 41373 14766 6790 45737 16792 10297
(97.3642653) (94.0441452) (82.3107244) (95.9541871) (94.6808113) (96.0633178) (93.8260094) (97.0482604) (97.1523959) (92.7333060) (80.6210251) (96.8581856) (82.4643661) (94.1664477) (97.3792778) (80.8641005) (93.2969235) (95.9738402)
100224610 - Information Techno
================================================================================
PAGE 6
================================================================================
D Government of Maharashtra
i State Common Entrance Test Cell
r Cut Off List for Maharashtra & Minority Seats of CAP Round I for Admission to First Year of Four Year
Degree Courses In Engineering and Technology & Master of Engineering and Technology (Integrated 5 Years) for the Year 2023-24
1012 - Government College of Engineering,Yavatmal
101219110 - Civil Engineering
Status: Government
Home University Seats Allotted to Home University Candidates
Stage GOPENH GSCH GVJH GNT2H GNT3H GOBCH LOPENH LSCH LNT1H LOBCH
I 74562 101880 80305 102191 117501 86831 82581 99853 94340 108125
(65.9622938) (47.3478734) (62.3996115) (46.8567142) (33.3408586) (58.1382561) (60.9799222) (49.0455617) (52.7422372) (42.5530244)
Home University Seats Allotted to Other Than Home University Candidates
Stage GSTH LSTH
I 124766 111381
(26.0127532) (39.4392454)
Other Than Home University Seats Allotted to Other Than Home University Candidates
Stage GOPENO GSCO GNT2O GOBCO LOPENO LSTO LOBCO
I 59087 82736 68148 86167 68951 123039 87157
(74.1356658) (60.9799222) (69.5976990) (58.5474069) (69.0354573) (27.6545345) (58.1195238)
State Level
Stage TFWS EWS
I 60201 96525
(73.4109953) (51.0567213)
Legends: Starting character G-General, L-Ladies, End character H-Home University, O-Other than Home University,S-State Level, AI- All India Seat.
Maharashtra State Seats - Cut Off Indicates Maharashtra State General Merit No.; Figures in bracket Indicates Merit Percentile.
1
================================================================================
PAGE 11
================================================================================
D Government of Maharashtra
i State Common Entrance Test Cell
r Cut Off List for Maharashtra & Minority Seats of CAP Round I for Admission to First Year of Four Year
Degree Courses In Engineering and Technology & Master of Engineering and Technology (Integrated 5 Years) for the Year 2023-24
1101 - Shri Sant Gajanan Maharaj College of Engineering,Shegaon
110124210 - Computer Science and Engineering
Status: Un-Aided
Home University Seats Allotted to Home University Candidates
Stage GOPENH GSCH GSTH GNT1H GOBCH LOPENH LSCH LSTH LVJH LOBCH PWDOPENH PWDROBC
H
I 14854 30173 93810 21316 15196 13862 25613 95619 42413 15422 71361 101841
(94.1055620) (87.6216398) (53.1660451) (91.3483231) (93.9947487) (94.5800123) (89.5398277) (52.2466614) (82.2266135) (93.8586283) (67.5703113) (47.3478734)
Other Than Home University Seats Allotted to Other Than Home University Candidates
Stage GOPENO GSCO GSTO GNT2O GNT3O GOBCO LOPENO LSCO LOBCO
I 15252 27151 103315 19753 35307 15664 14253 32854 15291
(93.9690179) (88.8621945) (46.1690466) (92.1155289) (85.3534944) (93.8067312) (94.3700831) (86.3770498) (93.9473684)
State Level
Stage DEFOPENS TFWS EWS
I 23928 7094 17134
(90.2424513) (97.2654813) (93.1305459)
Legends: Starting character G-General, L-Ladies, End character H-Home University, O-Other than Home University,S-State Level, AI- All India Seat.
Maharashtra State Seats - Cut Off Indicates Maharashtra State General Merit No.; Figures in bracket Indicates Merit Percentile.
1
================================================================================
PAGE 21
================================================================================
D Government of Maharashtra
i State Common Entrance Test Cell
r Cut Off List for Maharashtra & Minority Seats of CAP Round I for Admission to First Year of Four Year
Degree Courses In Engineering and Technology & Master of Engineering and Technology (Integrated 5 Years) for the Year 2023-24
1107 - P. R. Pote (Patil) Education & Welfare Trust's Group of Institution(Integrated Campus), Amravati
110729310 - Electrical Engineering
Status: Un-Aided
Home University Seats Allotted to Home University Candidates
Stage GOPENH GSCH GSTH GVJH GNT1H GNT3H GOBCH LOPENH LSCH LOBCH
I 75032 78031 93649 84531 76176 123928 77736 67938 82742 73395
(65.4207881) (63.6910141) (53.1660451) (59.8623853) (64.4805659) (26.7750310) (63.9730640) (69.5976990) (60.9799222) (66.4309764)
Other Than Home University Seats Allotted to Other Than Home University Candidates
Stage GOPENO GSCO GNT2O GOBCO LOPENO
I 90863 111219 116485 95327 81615
(55.4490884) (39.4392454) (34.1818319) (52.5521047) (61.4332053)
State Level
Stage TFWS EWS
I 63212 122902
(71.9809302) (28.1052376)
Legends: Starting character G-General, L-Ladies, End character H-Home University, O-Other than Home University,S-State Level, AI- All India Seat.
Maharashtra State Seats - Cut Off Indicates Maharashtra State General Merit No.; Figures in bracket Indicates Merit Percentile.
1
================================================================================
PAGE 51
================================================================================
D Government of Maharashtra
i State Common Entrance Test Cell
r Cut Off List for Maharashtra & Minority Seats of CAP Round I for Admission to First Year of Four Year
Degree Courses In Engineering and Technology & Master of Engineering and Technology (Integrated 5 Years) for the Year 2023-24
1121 - Shri Hanuman Vyayam Prasarak Mandals College of Engineering & Technology, Amravati
112124610 - Information Technology
Status: Un-Aided
Home University Seats Allotted to Home University Candidates
Stage GOPENH GSCH GSTH GVJH GNT1H GNT2H GNT3H GOBCH LOPENH LSCH LSTH LOBCH
I 58979 63170 72254 77499 68896 70668 90203 61924 55698 62651 139742 58854
(74.1935484) (71.9809302) (67.1534217) (64.0952985) (69.0354573) (67.9544349) (55.8997381) (73.0265619) (75.8958975) (72.3082536) (6.2955526) (74.1935484)
Other Than Home University Seats Allotted to Other Than Home University Candidates
Stage GOPENO GNT2O GOBCO LOPENO LSCO LVJO LOBCO
I 72340 106347 73541 75387 84781 139255 75486
(66.9527897) (43.5071268) (66.4309764) (65.3263316) (59.6839864) (7.2570822) (65.1075350)
Other Than Home University Seats Allotted to Home University Candidates
Stage GSTO
I 94187
(52.7523799)
State Level
Stage TFWS EWS
I 52189 85911
(77.7994669) (58.7124464)
Legends: Starting character G-General, L-Ladies, End character H-Home University, O-Other than Home University,S-State Level, AI- All India Seat.
Maharashtra State Seats - Cut Off Indicates Maharashtra State General Merit No.; Figures in bracket Indicates Merit
================================================================================
PAGE 101
================================================================================
D Government of Maharashtra
i State Common Entrance Test Cell
r Cut Off List for Maharashtra & Minority Seats of CAP Round I for Admission to First Year of Four Year
Degree Courses In Engineering and Technology & Master of Engineering and Technology (Integrated 5 Years) for the Year 2023-24
2008 - Government College of Engineering, Aurangabad
200819110 - Civil Engineering
Status: Government Autonomous
State Level
Stage GOPENS GSCS GSTS GVJS GNT1S GNT2S GNT3S GOBCS LOPENS LSCS LSTS LOBCS PWDOPENS DEFOPENS TFWS DEFRNT3S EWS
I 33859 53439 98230 45068 46898 43676 42184 43225 40833 50069 98214 59922 100205 110768 18661 117866 31619
(86.0392540) (76.8406961) (49.6513702) (81.0090469) (80.0793682) (81.5104589) (82.2515860) (81.8555930) (83.0041152) (78.4161664) (49.6513702) (73.4246062) (48.9725355) (39.9066862) (92.4862529) (32.8844711) (86.9739855)
200824210 - Computer Science and Engineering
Status: Government Autonomous
State Level
Stage GOPENS GSCS GSTS GVJS GNT2S GOBCS LOPENS LSCS LSTS LVJS LNT1S LNT2S LNT3S LOBCS PWDOPENS DEFOPENS TFWS PWDROBC DEFROBCS ORPHAN EWS
S
I 5904 12462 36659 6920 7012 6753 6610 23807 43479 12041 14171 16219 15546 8610 36056 12615 4126 67625 17327 104495 5727
(97.7289694) (95.1011675) (84.7409510) (97.3366305) (97.2746725) (97.3887196) (97.4695443) (90.2917336) (81.8534982) (95.2774853) (94.3936486) (93.5265773) (93.8260094) (96.6662904) (85.1537884) (95.0628437) (98.3935585) (69.6572694) (93.0962600) (45.6445719) (97.7845902)
200824610 - Information
================================================================================
PAGE 151
================================================================================
D Government of Maharashtra
i State Common Entrance Test Cell
r Cut Off List for Maharashtra & Minority Seats of CAP Round I for Admission to First Year of Four Year
Degree Courses In Engineering and Technology & Master of Engineering and Technology (Integrated 5 Years) for the Year 2023-24
2130 - Terna Public Charitable Trust's College of Engineering, Osmanabad
213019110 - Civil Engineering
Status: Un-Aided
Home University Seats Allotted to Home University Candidates
Stage GOPENH LOPENH
I 142386 137285
(1.8406961) (9.9924981)
Other Than Home University Seats Allotted to Other Than Home University Candidates
Stage GOPENO
I 99659
(49.2213366)
Other Than Home University Seats Allotted to Home University Candidates
Stage LOPENO
I 140270
(5.2963241)
State Level
Stage EWS
I 117774
(33.2472877)
Legends: Starting character G-General, L-Ladies, End character H-Home University, O-Other than Home University,S-State Level, AI- All India Seat.
Maharashtra State Seats - Cut Off Indicates Maharashtra State General Merit No.; Figures in bracket Indicates Merit Percentile.
1

In [15]:
with pdfplumber.open(pdf_path) as pdf:
    page = pdf.pages[5]      # Page 6 (0-indexed)
    table = page.extract_table()

table

[[None,
  'GOPENH',
  'GSCH',
  'GVJH',
  'GNT2H',
  'GNT3H',
  'GOBCH',
  'LOPENH',
  'LSCH',
  'LNT1H',
  'LOBCH'],
 ['I',
  '74562\n(65.9622938)',
  '101880\n(47.3478734)',
  '80305\n(62.3996115)',
  '102191\n(46.8567142)',
  '117501\n(33.3408586)',
  '86831\n(58.1382561)',
  '82581\n(60.9799222)',
  '99853\n(49.0455617)',
  '94340\n(52.7422372)',
  '108125\n(42.5530244)']]

In [16]:
with pdfplumber.open(pdf_path) as pdf:
    for i in range(5, 15):
        print("="*80)
        print("PAGE:", i+1)
        print("="*80)

        text = pdf.pages[i].extract_text()

        if text:
            print(text[:1200])

================================================================================
PAGE: 6
================================================================================
D Government of Maharashtra
i State Common Entrance Test Cell
r Cut Off List for Maharashtra & Minority Seats of CAP Round I for Admission to First Year of Four Year
Degree Courses In Engineering and Technology & Master of Engineering and Technology (Integrated 5 Years) for the Year 2023-24
1012 - Government College of Engineering,Yavatmal
101219110 - Civil Engineering
Status: Government
Home University Seats Allotted to Home University Candidates
Stage GOPENH GSCH GVJH GNT2H GNT3H GOBCH LOPENH LSCH LNT1H LOBCH
I 74562 101880 80305 102191 117501 86831 82581 99853 94340 108125
(65.9622938) (47.3478734) (62.3996115) (46.8567142) (33.3408586) (58.1382561) (60.9799222) (49.0455617) (52.7422372) (42.5530244)
Home University Seats Allotted to Other Than Home University Candidates
Stage GSTH LSTH
I 124766 111381
(26.0127532) (39.4392454)
Other Than Home University Seats Allotted to Other Than Home University Candidates
Stage GOPENO GSCO GNT2O GOBCO LOPENO LSTO LOBCO
I 59087 82736 68148 86167 68951 123039 87157
(74.1356658) (60.9799222) (69.5976990) (58.5474069) (69.0354573) (27.6545345) (58.1195238)
State Level
Stage TFWS EWS
I 60201 96525
(73.4109953) (51.0567213)
Legends: Starting chara
================================================================================
PAGE: 7
================================================================================
D Government of Maharashtra
i State Common Entrance Test Cell
r Cut Off List for Maharashtra & Minority Seats of CAP Round I for Admission to First Year of Four Year
Degree Courses In Engineering and Technology & Master of Engineering and Technology (Integrated 5 Years) for the Year 2023-24
1012 - Government College of Engineering,Yavatmal
101224510 - Computer Engineering
Status: Government
Home University Seats Allotted to Home University Candidates
Stage GOPENH GSCH GSTH GVJH GNT1H GNT2H GOBCH LOPENH LSCH LSTH LNT3H LOBCH PWDOPENH
I 31195 45916 69281 31317 32367 40791 32855 28640 42392 96270 81697 29760 109414
(87.2113119) (80.7328826) (68.9337823) (87.0718315) (86.6965956) (83.0041152) (86.3770498) (88.2793393) (82.2266135) (51.4762755) (61.4328470) (87.7770341) (41.0926455)
Home University Seats Allotted to Other Than Home University Candidates
Stage PWDROBC
H
I 112106
(38.9925740)
Other Than Home University Seats Allotted to Other Than Home University Candidates
Stage GOPENO GSCO GSTO GVJO GOBCO LOPENO LSCO LNT2O LOBCO
I 21624 28294 63337 28675 24413 24819 44126 27429 25524
(91.2518343) (88.2852988) (71.8303504) (88.2671548) (90.0942655) (89.9662416) (81.2345291) (88.7938441)
================================================================================
PAGE: 8
================================================================================
D Government of Maharashtra
i State Common Entrance Test Cell
r Cut Off List for Maharashtra & Minority Seats of CAP Round I for Admission to First Year of Four Year
Degree Courses In Engineering and Technology & Master of Engineering and Technology (Integrated 5 Years) for the Year 2023-24
1012 - Government College of Engineering,Yavatmal
101229310 - Electrical Engineering
Status: Government
Home University Seats Allotted to Home University Candidates
Stage GOPENH GSCH GVJH GNT1H GNT2H GNT3H GOBCH LOPENH LSCH LNT2H LOBCH
I 68570 80470 82248 80510 78055 136539 74433 64063 66750 68446 68856
(69.2172491) (62.3996115) (61.2935921) (61.6881259) (63.6910141) (11.2906846) (65.9622938) (71.6354089) (70.2813361) (69.3042857) (69.2172491)
Home University Seats Allotted to Other Than Home University Candidates
Stage GSTH LSTH
I 132632 121462
(16.3662375) (29.3464077)
Other Than Home University Seats Allotted to Other Than Home University Candidates
Stage GOPENO GSCO GSTO GOBCO LOPENO LSCO LVJO LNT3O LOBCO
I 59637 77027 79823 62352 67703 70293 136069 85978 69027
(73.6426530) (64.2666767) (62.4868401) (72.6119403) (69.6572694) (68.3823818) (11.6574699) (58.7124464) (69.0354573)
State Level
Sta
================================================================================
PAGE: 9
================================================================================
D Government of Maharashtra
i State Common Entrance Test Cell
r Cut Off List for Maharashtra & Minority Seats of CAP Round I for Admission to First Year of Four Year
Degree Courses In Engineering and Technology & Master of Engineering and Technology (Integrated 5 Years) for the Year 2023-24
1012 - Government College of Engineering,Yavatmal
101237210 - Electronics and Telecommunication Engg
Status: Government
Home University Seats Allotted to Home University Candidates
Stage GOPENH GSCH GVJH GNT1H GNT2H GNT3H GOBCH LOPENH LSCH LVJH LOBCH
I 48301 76557 63812 61377 72438 64496 52485 48581 54145 87291 50328
(79.5863208) (64.4512569) (71.6671025) (73.2522683) (66.9527897) (71.4000828) (77.4241933) (79.5208170) (76.7693871) (58.0840122) (78.4065273)
Home University Seats Allotted to Other Than Home University Candidates
Stage GSTH
I 101207
(47.3870980)
Other Than Home University Seats Allotted to Other Than Home University Candidates
Stage GOPENO GSCO GNT2O GOBCO LOPENO LSCO LSTO LNT1O LOBCO
I 36306 49474 49149 38766 36110 59896 90911 64668 37622
(85.1488129) (78.8754662) (79.2648162) (83.8780770) (85.1537884) (73.6426530) (55.4490884) (71.3590844) (84.3950599)
State Level
Stage DEFOPENS
================================================================================
PAGE: 10
================================================================================
D Government of Maharashtra
i State Common Entrance Test Cell
r Cut Off List for Maharashtra & Minority Seats of CAP Round I for Admission to First Year of Four Year
Degree Courses In Engineering and Technology & Master of Engineering and Technology (Integrated 5 Years) for the Year 2023-24
1012 - Government College of Engineering,Yavatmal
101261210 - Mechanical Engineering
Status: Government
Home University Seats Allotted to Home University Candidates
Stage GOPENH GSCH GVJH GNT2H GNT3H GOBCH LOPENH LSCH LNT1H LNT2H LOBCH PWDOPENH
I 80361 112853 102627 140543 85464 89267 93781 112711 107714 109381
(62.3996115) (37.7324111) (46.4534231) (5.0035420) (58.7429854) (56.6563970) (53.1660451) (38.8357386) (42.5955447) (41.0926455)
II 98438 142112
(49.6143282) (2.3315484)
Home University Seats Allotted to Other Than Home University Candidates
Stage GSTH LSTH
I 127867 129643
(22.6551453) (20.3198986)
Other Than Home University Seats Allotted to Other Than Home University Candidates
Stage GOPENO GSCO GSTO GVJO GNT1O GOBCO LOPENO LOBCO
I 61942 85079 129674 63008 63593 79624 81136 100650
(73.0265619) (58.8704519) (20.3198986) (71.9809302) (71.6671025) (62.7344336) (61.6397637) (48.0589023)
Sta
================================================================================
PAGE: 11
================================================================================
D Government of Maharashtra
i State Common Entrance Test Cell
r Cut Off List for Maharashtra & Minority Seats of CAP Round I for Admission to First Year of Four Year
Degree Courses In Engineering and Technology & Master of Engineering and Technology (Integrated 5 Years) for the Year 2023-24
1101 - Shri Sant Gajanan Maharaj College of Engineering,Shegaon
110124210 - Computer Science and Engineering
Status: Un-Aided
Home University Seats Allotted to Home University Candidates
Stage GOPENH GSCH GSTH GNT1H GOBCH LOPENH LSCH LSTH LVJH LOBCH PWDOPENH PWDROBC
H
I 14854 30173 93810 21316 15196 13862 25613 95619 42413 15422 71361 101841
(94.1055620) (87.6216398) (53.1660451) (91.3483231) (93.9947487) (94.5800123) (89.5398277) (52.2466614) (82.2266135) (93.8586283) (67.5703113) (47.3478734)
Other Than Home University Seats Allotted to Other Than Home University Candidates
Stage GOPENO GSCO GSTO GNT2O GNT3O GOBCO LOPENO LSCO LOBCO
I 15252 27151 103315 19753 35307 15664 14253 32854 15291
(93.9690179) (88.8621945) (46.1690466) (92.1155289) (85.3534944) (93.8067312) (94.3700831) (86.3770498) (93.9473684)
State Level
Stage DEFOPENS TFWS EWS
I 23928 7094 17134
(90.2424513) (97.2654813) (93.1305459
================================================================================
PAGE: 12
================================================================================
D Government of Maharashtra
i State Common Entrance Test Cell
r Cut Off List for Maharashtra & Minority Seats of CAP Round I for Admission to First Year of Four Year
Degree Courses In Engineering and Technology & Master of Engineering and Technology (Integrated 5 Years) for the Year 2023-24
1101 - Shri Sant Gajanan Maharaj College of Engineering,Shegaon
110124610 - Information Technology
Status: Un-Aided
Home University Seats Allotted to Home University Candidates
Stage GOPENH GSCH GSTH GVJH GNT1H GNT2H GOBCH LOPENH LSCH LNT3H LOBCH PWDOPENH PWDROBC
H
I 19526 37565 70085 26939 26676 24105 20546 17697 33446 30178 17917 101242 113116
(92.1548708) (84.4304792) (68.4014140) (88.9904805) (89.1600241) (90.1850615) (91.7186508) (92.9051391) (86.1668982) (87.6216398) (92.8392664) (47.3870980) (37.6936381)
Other Than Home University Seats Allotted to Other Than Home University Candidates
Stage GOPENO GSCO GVJO GOBCO LOPENO
I 16534 33829 34252 17148 20122
(93.4367098) (86.0392540) (85.9227307) (93.1305459) (91.8049290)
Other Than Home University Seats Allotted to Home University Candidates
Stage LSTO
I 113863
(36.6068088)
State Level
Stage DEFOPENS TFWS DEFROBCS EWS
I 37061 14193 42747 19270
================================================================================
PAGE: 13
================================================================================
D Government of Maharashtra
i State Common Entrance Test Cell
r Cut Off List for Maharashtra & Minority Seats of CAP Round I for Admission to First Year of Four Year
Degree Courses In Engineering and Technology & Master of Engineering and Technology (Integrated 5 Years) for the Year 2023-24
1101 - Shri Sant Gajanan Maharaj College of Engineering,Shegaon
110135610 - Electrical Engg[Electronics and Power]
Status: Un-Aided
Home University Seats Allotted to Home University Candidates
Stage GOPENH GSCH GSTH GVJH GNT2H GNT3H GOBCH LOPENH LSCH LOBCH
I 52831 66416 94732 80109 53997 61755 54163 46107 64394 49801
(77.4193548) (70.5106049) (52.5567137) (62.3996115) (76.7693871) (73.0265619) (76.7693871) (80.6210251) (71.4000828) (78.5775598)
Other Than Home University Seats Allotted to Other Than Home University Candidates
Stage GOPENO GSCO GNT1O GOBCO LOPENO LSCO LOBCO
I 65479 75970 86314 72066 59495 139056 66072
(71.1698646) (65.0367935) (58.5474069) (67.1534217) (74.0797795) (7.5928328) (70.6180504)
State Level
Stage TFWS EWS
I 29786 77843
(87.7770341) (63.9730640)
Legends: Starting character G-General, L-Ladies, End character H-Home University, O-Other than Home University,S-State Level,
================================================================================
PAGE: 14
================================================================================
D Government of Maharashtra
i State Common Entrance Test Cell
r Cut Off List for Maharashtra & Minority Seats of CAP Round I for Admission to First Year of Four Year
Degree Courses In Engineering and Technology & Master of Engineering and Technology (Integrated 5 Years) for the Year 2023-24
1101 - Shri Sant Gajanan Maharaj College of Engineering,Shegaon
110137210 - Electronics and Telecommunication Engg
Status: Un-Aided
Home University Seats Allotted to Home University Candidates
Stage GOPENH GSCH GSTH GNT1H GNT2H GNT3H GOBCH LOPENH LSCH LVJH LNT1H LNT2H LOBCH PWDOPENH
I 33662 51008 110733 52986 37986 44928 36753 34208 47231 64594 38234 34744 34988 141925
(86.0518493) (78.3308876) (39.9066862) (77.0079706) (84.2160540) (81.0174211) (84.5158411) (85.9227307) (79.8081214) (71.3590844) (84.2081516) (85.4752553) (85.4445126) (2.5768942)
Other Than Home University Seats Allotted to Other Than Home University Candidates
Stage GOPENO GSCO GVJO GNT2O GNT3O GOBCO LOPENO LSCO LOBCO
I 30906 58052 87898 37071 73312 35778 37742 57289 40123
(87.2543136) (75.0737739) (57.7272051) (84.4681938) (66.6716379) (85.1907088) (84.3950599) (75.1687111) (83.3483950)
State Level
Stage DEFOPENS TFWS EWS
I 11
================================================================================
PAGE: 15
================================================================================
D Government of Maharashtra
i State Common Entrance Test Cell
r Cut Off List for Maharashtra & Minority Seats of CAP Round I for Admission to First Year of Four Year
Degree Courses In Engineering and Technology & Master of Engineering and Technology (Integrated 5 Years) for the Year 2023-24
1101 - Shri Sant Gajanan Maharaj College of Engineering,Shegaon
110161210 - Mechanical Engineering
Status: Un-Aided
Home University Seats Allotted to Home University Candidates
Stage GOPENH GSCH GSTH GVJH GNT1H GNT2H GOBCH LOPENH LSCH LOBCH
I 64742 98947 138364 100540 69246 85364 67860 66884 89462 68338
(71.3590844) (49.5548073) (8.7187144) (48.0589023) (68.9337823) (58.8704519) (69.5976990) (69.7774101) (56.6563970) (69.3042857)
Other Than Home University Seats Allotted to Other Than Home University Candidates
Stage GOPENO GSCO GOBCO LOPENO LOBCO
I 76034 92734 84297 53945 91054
(65.0367935) (54.0043616) (59.9156802) (76.8390440) (55.2985075)
Other Than Home University Seats Allotted to Home University Candidates
Stage LNT2O
I 135572
(12.6949825)
State Level
Stage DEFOPENS TFWS EWS
I 135898 36571 91122
(12.1380345) (84.7409510) (55.2985075)
Legends: Starting character G-General, L-Ladies, End ch

In [17]:
with pdfplumber.open(pdf_path) as pdf:
    page = pdf.pages[5]

    print(page.extract_text())

D Government of Maharashtra
i State Common Entrance Test Cell
r Cut Off List for Maharashtra & Minority Seats of CAP Round I for Admission to First Year of Four Year
Degree Courses In Engineering and Technology & Master of Engineering and Technology (Integrated 5 Years) for the Year 2023-24
1012 - Government College of Engineering,Yavatmal
101219110 - Civil Engineering
Status: Government
Home University Seats Allotted to Home University Candidates
Stage GOPENH GSCH GVJH GNT2H GNT3H GOBCH LOPENH LSCH LNT1H LOBCH
I 74562 101880 80305 102191 117501 86831 82581 99853 94340 108125
(65.9622938) (47.3478734) (62.3996115) (46.8567142) (33.3408586) (58.1382561) (60.9799222) (49.0455617) (52.7422372) (42.5530244)
Home University Seats Allotted to Other Than Home University Candidates
Stage GSTH LSTH
I 124766 111381
(26.0127532) (39.4392454)
Other Than Home University Seats Allotted to Other Than Home University Candidates
Stage GOPENO GSCO GNT2O GOBCO LOPENO LSTO LOBCO
I 59087 82736 68148 86167 68951 123039 87157
(74.1356658) (60.9799222) (69.5976990) (58.5474069) (69.0354573) (27.6545345) (58.1195238)
State Level
Stage TFWS EWS
I 60201 96525
(73.4109953) (51.0567213)
Legends: Starting character G-General, L-Ladies, End character H-Home University, O-Other than Home University,S-State Level, AI- All India Seat.
Maharashtra State Seats - Cut Off Indicates Maharashtra State General Merit No.; Figures in bracket Indicates Merit Percentile.
1

In [19]:
import re

with pdfplumber.open(pdf_path) as pdf:
    text = pdf.pages[5].extract_text()

# College Code + College Name
college_match = re.search(
    r'^\s*(\d{4})\s*-\s*(.+)$',
    text,
    re.MULTILINE
)

# Branch Code + Branch Name
branch_match = re.search(r'(\d{9})\s*-\s*(.+)', text)

# Status
status_match = re.search(r'Status:\s*(.+)', text)

college_code = college_match.group(1) if college_match else None
college_name = college_match.group(2).strip() if college_match else None

branch_code = branch_match.group(1) if branch_match else None
branch_name = branch_match.group(2).strip() if branch_match else None

status = status_match.group(1).strip() if status_match else None

print("College Code :", college_code)
print("College Name :", college_name)
print("Branch Code  :", branch_code)
print("Branch Name  :", branch_name)
print("Status       :", status)

College Code : 1012
College Name : Government College of Engineering,Yavatmal
Branch Code  : 101219110
Branch Name  : Civil Engineering
Status       : Government

In [20]:
with pdfplumber.open(pdf_path) as pdf:
    page = pdf.pages[5]
    table = page.extract_table()

for row in table:
    print(row)

[None, 'GOPENH', 'GSCH', 'GVJH', 'GNT2H', 'GNT3H', 'GOBCH', 'LOPENH', 'LSCH', 'LNT1H', 'LOBCH']
['I', '74562\n(65.9622938)', '101880\n(47.3478734)', '80305\n(62.3996115)', '102191\n(46.8567142)', '117501\n(33.3408586)', '86831\n(58.1382561)', '82581\n(60.9799222)', '99853\n(49.0455617)', '94340\n(52.7422372)', '108125\n(42.5530244)']

In [21]:
rows = []

# Metadata
metadata = {
    "academic_year": "2023-2024",
    "college_code": college_code,
    "college_name": college_name,
    "branch_code": branch_code,
    "branch_name": branch_name,
    "status": status
}

# First table only
headers = table[0][1:]      # GOPENH, GSCH, GVJH...
values = table[1][1:]       # 74562\n(65.96)...

stage = table[1][0]         # I

for category, value in zip(headers, values):

    merit_rank = None
    percentile = None

    if value:
        parts = value.split("\n")

        if len(parts) == 2:
            merit_rank = parts[0]
            percentile = parts[1].replace("(", "").replace(")", "")

    rows.append({
        **metadata,
        "seat_category": category,
        "stage": stage,
        "merit_rank": merit_rank,
        "percentile": percentile
    })

df = pd.DataFrame(rows)

df

,academic_year,college_code,college_name,branch_code,branch_name,status,seat_category,stage,merit_rank,percentile
0,2023-2024,1012,"Government College of Engineering,Yavatmal",101219110,Civil Engineering,Government,GOPENH,I,74562,65.9622938
1,2023-2024,1012,"Government College of Engineering,Yavatmal",101219110,Civil Engineering,Government,GSCH,I,101880,47.3478734
2,2023-2024,1012,"Government College of Engineering,Yavatmal",101219110,Civil Engineering,Government,GVJH,I,80305,62.3996115
3,2023-2024,1012,"Government College of Engineering,Yavatmal",101219110,Civil Engineering,Government,GNT2H,I,102191,46.8567142
4,2023-2024,1012,"Government College of Engineering,Yavatmal",101219110,Civil Engineering,Government,GNT3H,I,117501,33.3408586
5,2023-2024,1012,"Government College of Engineering,Yavatmal",101219110,Civil Engineering,Government,GOBCH,I,86831,58.1382561
6,2023-2024,1012,"Government College of Engineering,Yavatmal",101219110,Civil Engineering,Government,LOPENH,I,82581,60.9799222
7,2023-2024,1012,"Government College of Engineering,Yavatmal",101219110,Civil Engineering,Government,LSCH,I,99853,49.0455617
8,2023-2024,1012,"Government College of Engineering,Yavatmal",101219110,Civil Engineering,Government,LNT1H,I,94340,52.7422372
9,2023-2024,1012,"Government College of Engineering,Yavatmal",101219110,Civil Engineering,Government,LOBCH,I,108125,42.5530244

In [22]:
def extract_metadata(text, academic_year):
    import re

    college_match = re.search(
        r'^\s*(\d{4})\s*-\s*(.+)$',
        text,
        re.MULTILINE
    )

    branch_match = re.search(
        r'(\d{9})\s*-\s*(.+)',
        text
    )

    status_match = re.search(
        r'Status:\s*(.+)',
        text
    )

    metadata = {
        "academic_year": academic_year,
        "college_code": college_match.group(1) if college_match else None,
        "college_name": college_match.group(2).strip() if college_match else None,
        "branch_code": branch_match.group(1) if branch_match else None,
        "branch_name": branch_match.group(2).strip() if branch_match else None,
        "status": status_match.group(1).strip() if status_match else None
    }

    return metadata

In [23]:
with pdfplumber.open(pdf_path) as pdf:
    text = pdf.pages[5].extract_text()

metadata = extract_metadata(text, "2023-2024")

metadata

{'academic_year': '2023-2024',
 'college_code': '1012',
 'college_name': 'Government College of Engineering,Yavatmal',
 'branch_code': '101219110',
 'branch_name': 'Civil Engineering',
 'status': 'Government'}

In [28]:
from src.components.data_extraction import extract_metadata, extract_table

In [29]:
with pdfplumber.open(pdf_path) as pdf:

    page = pdf.pages[5]

    text = page.extract_text()

    table = page.extract_table()

metadata = extract_metadata(text, "2023-2024")

df = extract_table(table, metadata)

df.head()

,academic_year,college_code,college_name,branch_code,branch_name,status,seat_category,stage,merit_rank,percentile
0,2023-2024,1012,"Government College of Engineering,Yavatmal",101219110,Civil Engineering,Government,GOPENH,I,74562,65.9622938
1,2023-2024,1012,"Government College of Engineering,Yavatmal",101219110,Civil Engineering,Government,GSCH,I,101880,47.3478734
2,2023-2024,1012,"Government College of Engineering,Yavatmal",101219110,Civil Engineering,Government,GVJH,I,80305,62.3996115
3,2023-2024,1012,"Government College of Engineering,Yavatmal",101219110,Civil Engineering,Government,GNT2H,I,102191,46.8567142
4,2023-2024,1012,"Government College of Engineering,Yavatmal",101219110,Civil Engineering,Government,GNT3H,I,117501,33.3408586