In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("../dataset/final/cleaned_dataset.csv")

df.shape

(84076, 11)

In [4]:
import sys
import os

project_root = os.path.abspath("..")

if project_root not in sys.path:
    sys.path.append(project_root)

In [5]:
from importlib import reload
import src.components.recommendation_engine as rec

reload(rec)

from src.components.recommendation_engine import RecommendationEngine

engine = RecommendationEngine(df)

In [6]:
engine.df.head()

,academic_year,college_code,college_name,branch_code,branch_name,status,section,category,stage,merit_rank,percentile
0,2023-2024,1002,"Government College of Engineering, Amravati",100219110,Civil Engineering,Government Autonomous,Home University,GOPENS,I,45820,80.732883
1,2023-2024,1002,"Government College of Engineering, Amravati",100219110,Civil Engineering,Government Autonomous,Home University,GSCS,I,54803,76.616654
2,2023-2024,1002,"Government College of Engineering, Amravati",100219110,Civil Engineering,Government Autonomous,Home University,GSTS,I,85528,58.742985
3,2023-2024,1002,"Government College of Engineering, Amravati",100219110,Civil Engineering,Government Autonomous,Home University,GVJS,I,53198,76.921342
4,2023-2024,1002,"Government College of Engineering, Amravati",100219110,Civil Engineering,Government Autonomous,Home University,GNT1S,I,55202,76.284368

In [7]:
branch_df = engine.filter_branch(
    "Computer Engineering"
)

branch_df.head()

,academic_year,college_code,college_name,branch_code,branch_name,status,section,category,stage,merit_rank,percentile
170,2023-2024,1012,"Government College of Engineering,Yavatmal",101224510,Computer Engineering,Government,Home University,GOPENH,I,31195,87.211312
171,2023-2024,1012,"Government College of Engineering,Yavatmal",101224510,Computer Engineering,Government,Home University,GSCH,I,45916,80.732883
172,2023-2024,1012,"Government College of Engineering,Yavatmal",101224510,Computer Engineering,Government,Home University,GSTH,I,69281,68.933782
173,2023-2024,1012,"Government College of Engineering,Yavatmal",101224510,Computer Engineering,Government,Home University,GVJH,I,31317,87.071832
174,2023-2024,1012,"Government College of Engineering,Yavatmal",101224510,Computer Engineering,Government,Home University,GNT1H,I,32367,86.696596

In [8]:
branch_df.shape

(11642, 11)

In [9]:
import os

print(os.getcwd())

c:\college predictor\notebook

In [10]:
import src.logger as lg

print(lg.LOG_FILE_PATH)

c:\college predictor\logs\07_02_2026_23_05_11.log

In [11]:
branch_df = engine.filter_branch(
    "Computer Engineering"
)

category_df = engine.filter_category(
    branch_df,
    "GOPENH"
)

category_df.shape

(460, 11)

In [12]:
branch_df = engine.filter_branch(
    "Computer Engineering"
)

category_df = engine.filter_category(
    branch_df,
    "GOPENH"
)

year_df = engine.filter_year(
    category_df,
    "2025-2026"
)

year_df.shape

(159, 11)

In [13]:
year_df[
    [
        "college_name",
        "branch_name",
        "category",
        "academic_year",
        "percentile"
    ]
].head(10)

,college_name,branch_name,category,academic_year,percentile
53763,"Government College of Engineering,Yavatmal",Computer Engineering,GOPENH,2025-2026,87.129889
55508,"Manav School of Engineering & Technology, Gut ...",Computer Engineering,GOPENH,2025-2026,70.872294
57522,Vilasrao Deshmukh Foundation Group of Institut...,Computer Engineering,GOPENH,2025-2026,67.844082
57599,Aditya Education Trust's Mitthulalji Sarada Po...,Computer Engineering,GOPENH,2025-2026,12.562027
57642,GRAMIN TECHNICAL AND MANAGEMENT CAMPUS NANDED.,Computer Engineering,GOPENH,2025-2026,57.253756
57813,STMEI's Sandipani Technical Campus-Faculty of ...,Computer Engineering,GOPENH,2025-2026,53.769478
58060,Jijau Institute of Engineering Technology and ...,Computer Engineering,GOPENH,2025-2026,0.492319
58062,Jijau Institute of Engineering Technology and ...,Computer Engineering,GOPENH,2025-2026,18.702808
58970,Manjara Charitable Trust's Rajiv Gandhi Instit...,Computer Engineering,GOPENH,2025-2026,95.715414
59222,"Thakur Shyamnarayan Engineering College, Mumbai",Computer Engineering,GOPENH,2025-2026,94.782972

In [14]:
branch_df = engine.filter_branch(
    "Computer Engineering"
)

category_df = engine.filter_category(
    branch_df,
    "GOPENH"
)

year_df = engine.filter_year(
    category_df,
    "2025-2026"
)

year_df.shape

(159, 11)

In [15]:
year_df[
    [
        "college_name",
        "branch_name",
        "category",
        "academic_year",
        "percentile"
    ]
].head(10)

,college_name,branch_name,category,academic_year,percentile
53763,"Government College of Engineering,Yavatmal",Computer Engineering,GOPENH,2025-2026,87.129889
55508,"Manav School of Engineering & Technology, Gut ...",Computer Engineering,GOPENH,2025-2026,70.872294
57522,Vilasrao Deshmukh Foundation Group of Institut...,Computer Engineering,GOPENH,2025-2026,67.844082
57599,Aditya Education Trust's Mitthulalji Sarada Po...,Computer Engineering,GOPENH,2025-2026,12.562027
57642,GRAMIN TECHNICAL AND MANAGEMENT CAMPUS NANDED.,Computer Engineering,GOPENH,2025-2026,57.253756
57813,STMEI's Sandipani Technical Campus-Faculty of ...,Computer Engineering,GOPENH,2025-2026,53.769478
58060,Jijau Institute of Engineering Technology and ...,Computer Engineering,GOPENH,2025-2026,0.492319
58062,Jijau Institute of Engineering Technology and ...,Computer Engineering,GOPENH,2025-2026,18.702808
58970,Manjara Charitable Trust's Rajiv Gandhi Instit...,Computer Engineering,GOPENH,2025-2026,95.715414
59222,"Thakur Shyamnarayan Engineering College, Mumbai",Computer Engineering,GOPENH,2025-2026,94.782972

In [16]:
classified_df = engine.classify(
    year_df,
    percentile=98.2
)

In [17]:
classified_df[
    [
        "college_name",
        "percentile",
        "difference",
        "chance"
    ]
].head(20)

,college_name,percentile,difference,chance
53763,"Government College of Engineering,Yavatmal",87.129889,11.070111,Safe
55508,"Manav School of Engineering & Technology, Gut ...",70.872294,27.327706,Safe
57522,Vilasrao Deshmukh Foundation Group of Institut...,67.844082,30.355918,Safe
57599,Aditya Education Trust's Mitthulalji Sarada Po...,12.562027,85.637973,Safe
57642,GRAMIN TECHNICAL AND MANAGEMENT CAMPUS NANDED.,57.253756,40.946244,Safe
57813,STMEI's Sandipani Technical Campus-Faculty of ...,53.769478,44.430522,Safe
58060,Jijau Institute of Engineering Technology and ...,0.492319,97.707681,Safe
58062,Jijau Institute of Engineering Technology and ...,18.702808,79.497192,Safe
58970,Manjara Charitable Trust's Rajiv Gandhi Instit...,95.715414,2.484586,Safe
59222,"Thakur Shyamnarayan Engineering College, Mumbai",94.782972,3.417028,Safe
59252,Jawahar Education Society's Annasaheb Chudaman...,88.781302,9.418698,Safe
59409,"Saraswati Education Society, Yadavrao Tasgaonk...",81.709831,16.490169,Safe
59528,Saraswati Education Society's Saraswati Colleg...,90.292154,7.907846,Safe
59672,M.G.M.'s College of Engineering and Technology...,87.815228,10.384772,Safe
59917,"Thadomal Shahani Engineering College, Bandra, ...",98.794695,-0.594695,Dream
59952,Anjuman-I-Islam's M.H. Saboo Siddik College of...,89.322337,8.877663,Safe
60052,"N.Y.S.S.'s Datta Meghe College of Engineering,...",92.848822,5.351178,Safe
60228,Vasantdada Patil Pratishthan's College Of Engi...,92.848822,5.351178,Safe
60348,"Bharati Vidyapeeth College of Engineering, Nav...",94.753689,3.446311,Safe
60513,"Terna Engineering College, Nerul, Navi Mumbai",93.540689,4.659311,Safe

In [18]:
classified_df["chance"].value_counts()

chance
Safe      157
Dream       1
Target      1
Name: count, dtype: int64

In [19]:
safe_df = classified_df[
    classified_df["chance"] == "Safe"
]

target_df = classified_df[
    classified_df["chance"] == "Target"
]

dream_df = classified_df[
    classified_df["chance"] == "Dream"
]

In [20]:
print(len(safe_df))
print(len(target_df))
print(len(dream_df))

157
1
1

In [21]:
from importlib import reload
import src.components.recommendation_engine as rec

reload(rec)

from src.components.recommendation_engine import RecommendationEngine

engine = RecommendationEngine(df)

In [22]:
result = engine.recommend(
    percentile=98.2,
    category="GOPENH",
    branch="Computer Engineering",
    academic_year="2025-2026"
)

result.head()

AttributeError: 'dict' object has no attribute 'head'

In [23]:
from importlib import reload
import src.components.recommendation_engine as rec

reload(rec)

from src.components.recommendation_engine import RecommendationEngine

engine = RecommendationEngine(df)

In [24]:
result = engine.recommend(
    percentile=98.2,
    category="GOPENH",
    branch="Computer Engineering",
    academic_year="2025-2026"
)

result[
    [
        "college_name",
        "percentile",
        "difference",
        "chance"
    ]
].head(20)

TypeError: unhashable type: 'list'

In [ ]:
from importlib import reload
import src.components.recommendation_engine as rec

reload(rec)

from src.components.recommendation_engine import RecommendationEngine

engine = RecommendationEngine(df)

In [ ]:
result = engine.recommend(
    percentile=98.2,
    category="GOPENH",
    branch="Computer Engineering",
    academic_year="2025-2026"
)

In [ ]:
result.keys()

dict_keys(['safe', 'target', 'dream'])

In [ ]:
result["safe"].head()

,academic_year,college_code,college_name,branch_code,branch_name,status,section,category,stage,merit_rank,percentile,difference,chance
58060,2025-2026,2637,Jijau Institute of Engineering Technology and ...,263724510,Computer Engineering,Un-Aided,Home University,GOPENH,I,179296,0.492319,97.707681,Safe
82805,2025-2026,6799,"Shivganga Charitable Trust, Sangli Vishveshwar...",679924510,Computer Engineering,Un-Aided,State Level,GOPENH,I,176887,3.895894,94.304106,Safe
82801,2025-2026,6799,"Shivganga Charitable Trust, Sangli Vishveshwar...",679924510,Computer Engineering,Un-Aided,Home University (Other Than HU),GOPENH,I,175642,5.650827,92.549173,Safe
82800,2025-2026,6799,"Shivganga Charitable Trust, Sangli Vishveshwar...",679924510,Computer Engineering,Un-Aided,Home University,GOPENH,I,173252,8.531383,89.668617,Safe
57599,2025-2026,2282,Aditya Education Trust's Mitthulalji Sarada Po...,228224510,Computer Engineering,Un-Aided,Home University,GOPENH,I,169915,12.562027,85.637973,Safe

In [ ]:
result["target"].head()

,academic_year,college_code,college_name,branch_code,branch_name,status,section,category,stage,merit_rank,percentile,difference,chance
76404,2025-2026,6274,Pune Vidyarthi Griha's College of Engineering ...,627424510,Computer Engineering,Un-Aided,Home University,GOPENH,I,6718,97.756002,0.443998,Target

In [ ]:
result["dream"].head()

,academic_year,college_code,college_name,branch_code,branch_name,status,section,category,stage,merit_rank,percentile,difference,chance
59917,2025-2026,3182,"Thadomal Shahani Engineering College, Bandra, ...",318224510,Computer Engineering,Un-Aided Linguistic Minority - Sindhi,Home University,GOPENH,I,3456,98.794695,-0.594695,Dream

In [ ]:
from importlib import reload
import src.components.recommendation_engine as rec

reload(rec)

from src.components.recommendation_engine import RecommendationEngine

engine = RecommendationEngine(df)

In [ ]:
result = engine.recommend(
    percentile=98.2,
    category="GOPENH",
    branch="Computer Engineering",
    academic_year="2025-2026"
)

In [ ]:
len(result["safe"])
len(result["target"])
len(result["dream"])

1

In [ ]:
safe = result["safe"]

safe.duplicated(
    subset=["college_code", "branch_code"]
).sum()

0

In [ ]:
from importlib import reload
import src.components.recommendation_engine as rec

reload(rec)

from src.components.recommendation_engine import RecommendationEngine

engine = RecommendationEngine(df)

In [ ]:
result = engine.recommend(
    percentile=98.2,
    category="GOPENH",
    branch="Computer Engineering",
    academic_year="2025-2026"
)

In [ ]:
result["safe"].head()

result["target"].head()

result["dream"].head()

,academic_year,college_code,college_name,branch_code,branch_name,status,section,category,stage,merit_rank,percentile,difference,chance
59917,2025-2026,3182,"Thadomal Shahani Engineering College, Bandra, ...",318224510,Computer Engineering,Un-Aided Linguistic Minority - Sindhi,Home University,GOPENH,I,3456,98.794695,-0.594695,Dream

In [ ]:
from importlib import reload
import src.components.recommendation_engine as rec

reload(rec)

from src.components.recommendation_engine import RecommendationEngine

engine = RecommendationEngine(df)

In [ ]:
result = engine.recommend(
    percentile=98.2,
    category="GOPENH",
    branch="Computer Engineering",
    academic_year="2025-2026"
)

In [ ]:
result["safe"][
    [
        "college_name",
        "difference",
        "confidence"
    ]
].head()

,college_name,difference,confidence
82800,"Shivganga Charitable Trust, Sangli Vishveshwar...",89.668617,99
57599,Aditya Education Trust's Mitthulalji Sarada Po...,85.637973,99
70612,"MKD Institute of Technology, Nadurbar",80.423383,99
58062,Jijau Institute of Engineering Technology and ...,79.497192,99
70349,"Maulana Mukhtar Ahmad Nadvi Technical Campus, ...",75.971775,99

In [ ]:
from importlib import reload
import src.components.recommendation_engine as rec

reload(rec)

from src.components.recommendation_engine import RecommendationEngine

engine = RecommendationEngine(df)

In [ ]:
result = engine.recommend(
    percentile=98.2,
    category="GOPENH",
    branch="Computer Engineering",
    academic_year="2025-2026"
)

In [ ]:
result["safe"][
    [
        "college_name",
        "difference",
        "confidence"
    ]
].head()

,college_name,difference,confidence
82800,"Shivganga Charitable Trust, Sangli Vishveshwar...",89.668617,99
57599,Aditya Education Trust's Mitthulalji Sarada Po...,85.637973,99
70612,"MKD Institute of Technology, Nadurbar",80.423383,99
58062,Jijau Institute of Engineering Technology and ...,79.497192,99
70349,"Maulana Mukhtar Ahmad Nadvi Technical Campus, ...",75.971775,99

In [ ]:
result = engine.recommend(
    percentile=98.2,
    category="GOPENH",
    branch="Computer Engineering"
)

In [ ]:
result["safe"][
    [
        "college_name",
        "difference",
        "confidence"
    ]
].head()

,college_name,difference,confidence
82800,"Shivganga Charitable Trust, Sangli Vishveshwar...",89.668617,99
57599,Aditya Education Trust's Mitthulalji Sarada Po...,85.637973,99
70612,"MKD Institute of Technology, Nadurbar",80.423383,99
58062,Jijau Institute of Engineering Technology and ...,79.497192,99
70349,"Maulana Mukhtar Ahmad Nadvi Technical Campus, ...",75.971775,99

In [ ]:
from importlib import reload
import src.components.recommendation_engine as rec

reload(rec)

from src.components.recommendation_engine import RecommendationEngine

engine = RecommendationEngine(df)

In [ ]:
result = engine.recommend(
    percentile=98.2,
    category="GOPENH",
    branch="Computer Engineering"
)

In [ ]:
result.keys()

dict_keys(['topRecommendation', 'safe', 'target', 'dream'])

In [ ]:
result["topRecommendation"]

academic_year                                            2025-2026
college_code                                                  6799
college_name     Shivganga Charitable Trust, Sangli Vishveshwar...
branch_code                                              679924510
branch_name                                   Computer Engineering
status                                                    Un-Aided
section                                            Home University
category                                                    GOPENH
stage                                                            I
merit_rank                                                  173252
percentile                                                8.531383
difference                                               89.668617
chance                                                        Safe
confidence                                                      99
Name: 82800, dtype: object

In [ ]:
from importlib import reload
import src.components.recommendation_engine as rec

reload(rec)

from src.components.recommendation_engine import RecommendationEngine

engine = RecommendationEngine(df)

In [ ]:
result = engine.recommend(
    percentile=98.2,
    category="GOPENH",
    branch="Computer Engineering"
)

In [ ]:
from importlib import reload
import src.components.recommendation_engine as rec

reload(rec)

from src.components.recommendation_engine import RecommendationEngine

engine = RecommendationEngine(df)

In [25]:
import os

os.makedirs("artifacts", exist_ok=True)

df.to_csv(
    "artifacts/master_dataset.csv",
    index=False
)

print("Dataset saved successfully.")

Dataset saved successfully.

In [ ]:
import os

os.path.exists("artifacts/master_dataset.csv")

True

In [ ]:
import pandas as pd

test = pd.read_csv("artifacts/master_dataset.csv")

print(test.shape)

(84076, 11)

In [26]:
print(df["category"].unique())

['GOPENS' 'GSCS' 'GSTS' 'GVJS' 'GNT1S' 'GNT2S' 'GNT3S' 'GOBCS' 'LOPENS'
 'LSCS' 'LSTS' 'LVJS' 'LNT1S' 'LNT2S' 'LNT3S' 'LOBCS' 'PWDOPENS'
 'DEFOPENS' 'TFWS' 'EWS' 'PWDROBCS' 'DEFROBCS' 'PWDRSCS' 'GOPENH' 'GSCH'
 'GVJH' 'GNT1H' 'GOBCH' 'LOPENH' 'LOBCH' 'GOPENO' 'GSCO' 'GNT3O' 'GOBCO'
 'LOPENO' 'LSCH' 'GSTH' 'GNT2H' 'GNT3H' 'LNT1H' 'LSTH' 'GNT2O' 'LSTO'
 'LOBCO' 'LNT3H' 'PWDOPENH' 'PWDROBCH' 'GSTO' 'GVJO' 'LSCO' 'LNT2O'
 'LNT2H' 'LVJO' 'LNT3O' 'LVJH' 'LNT1O' 'GNT1O' 'PWDOBCS' 'DEFOBCS'
 'DEFRSCS' 'ORPHAN' 'MI' 'DEFRNT3S' 'DEFRNT2S' 'DEFRNT1S' 'DEFRVJS'
 'PWDRNT2S' 'PWDSCS' 'DEFSCS' 'PWDRNT3S' 'PWDRSCH' 'PWDRNT1S' 'PWDRSTS'
 'PWDOBCH' 'PWDRNT2H' 'PWDSCH' 'PWDRNT1H' 'PWDRSTH' 'PWDRVJH' 'GSEBCS'
 'LSEBCS' 'DEFRSEBCS' 'GSEBCH' 'LSEBCH' 'GSEBCO' 'LSEBCO' 'PWDRSEBCS'
 'DEFSEBCS' 'PWDSEBCS' 'PWDRVJS' 'PWDRSEBCH' 'DEFSTS']